//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SLangGrammar.g4 by ANTLR 4.6.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SLangGrammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISLangGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5")]
[System.CLSCompliant(false)]
public partial class SLangGrammarBaseListener : ISLangGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] SLangGrammarParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] SLangGrammarParser.StartContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.moduleImport"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModuleImport([NotNull] SLangGrammarParser.ModuleImportContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.moduleImport"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModuleImport([NotNull] SLangGrammarParser.ModuleImportContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule([NotNull] SLangGrammarParser.ModuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule([NotNull] SLangGrammarParser.ModuleContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.moduleStatementsSeq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModuleStatementsSeq([NotNull] SLangGrammarParser.ModuleStatementsSeqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.moduleStatementsSeq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModuleStatementsSeq([NotNull] SLangGrammarParser.ModuleStatementsSeqContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.moduleDeclareSeq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModuleDeclareSeq([NotNull] SLangGrammarParser.ModuleDeclareSeqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.moduleDeclareSeq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModuleDeclareSeq([NotNull] SLangGrammarParser.ModuleDeclareSeqContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.declare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclare([NotNull] SLangGrammarParser.DeclareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.declare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclare([NotNull] SLangGrammarParser.DeclareContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.variableDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDecl([NotNull] SLangGrammarParser.VariableDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.variableDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDecl([NotNull] SLangGrammarParser.VariableDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.simpleDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleDecl([NotNull] SLangGrammarParser.SimpleDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.simpleDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleDecl([NotNull] SLangGrammarParser.SimpleDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.arrayDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayDecl([NotNull] SLangGrammarParser.ArrayDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.arrayDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayDecl([NotNull] SLangGrammarParser.ArrayDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.arrayDeclType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayDeclType([NotNull] SLangGrammarParser.ArrayDeclTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.arrayDeclType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayDeclType([NotNull] SLangGrammarParser.ArrayDeclTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.ptrDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPtrDecl([NotNull] SLangGrammarParser.PtrDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.ptrDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPtrDecl([NotNull] SLangGrammarParser.PtrDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.constDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstDecl([NotNull] SLangGrammarParser.ConstDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.constDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstDecl([NotNull] SLangGrammarParser.ConstDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.moduleFieldDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModuleFieldDecl([NotNull] SLangGrammarParser.ModuleFieldDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.moduleFieldDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModuleFieldDecl([NotNull] SLangGrammarParser.ModuleFieldDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] SLangGrammarParser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] SLangGrammarParser.TypeNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.ptrType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPtrType([NotNull] SLangGrammarParser.PtrTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.ptrType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPtrType([NotNull] SLangGrammarParser.PtrTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.customType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCustomType([NotNull] SLangGrammarParser.CustomTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.customType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCustomType([NotNull] SLangGrammarParser.CustomTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.scalarType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScalarType([NotNull] SLangGrammarParser.ScalarTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.scalarType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScalarType([NotNull] SLangGrammarParser.ScalarTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.simpleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleType([NotNull] SLangGrammarParser.SimpleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.simpleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleType([NotNull] SLangGrammarParser.SimpleTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayType([NotNull] SLangGrammarParser.ArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayType([NotNull] SLangGrammarParser.ArrayTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.arrayDimention"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayDimention([NotNull] SLangGrammarParser.ArrayDimentionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.arrayDimention"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayDimention([NotNull] SLangGrammarParser.ArrayDimentionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.typeDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDecl([NotNull] SLangGrammarParser.TypeDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.typeDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDecl([NotNull] SLangGrammarParser.TypeDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.typeInherit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeInherit([NotNull] SLangGrammarParser.TypeInheritContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.typeInherit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeInherit([NotNull] SLangGrammarParser.TypeInheritContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.typeFieldDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeFieldDecl([NotNull] SLangGrammarParser.TypeFieldDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.typeFieldDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeFieldDecl([NotNull] SLangGrammarParser.TypeFieldDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.functionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDecl([NotNull] SLangGrammarParser.FunctionDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.functionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDecl([NotNull] SLangGrammarParser.FunctionDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.thisHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThisHeader([NotNull] SLangGrammarParser.ThisHeaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.thisHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThisHeader([NotNull] SLangGrammarParser.ThisHeaderContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.routineArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoutineArgList([NotNull] SLangGrammarParser.RoutineArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.routineArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoutineArgList([NotNull] SLangGrammarParser.RoutineArgListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.routineArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoutineArg([NotNull] SLangGrammarParser.RoutineArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.routineArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoutineArg([NotNull] SLangGrammarParser.RoutineArgContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.procedureDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureDecl([NotNull] SLangGrammarParser.ProcedureDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.procedureDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureDecl([NotNull] SLangGrammarParser.ProcedureDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.importHead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportHead([NotNull] SLangGrammarParser.ImportHeadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.importHead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportHead([NotNull] SLangGrammarParser.ImportHeadContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.statementSeq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementSeq([NotNull] SLangGrammarParser.StatementSeqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.statementSeq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementSeq([NotNull] SLangGrammarParser.StatementSeqContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] SLangGrammarParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] SLangGrammarParser.StatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.simpleStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleStatement([NotNull] SLangGrammarParser.SimpleStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.simpleStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleStatement([NotNull] SLangGrammarParser.SimpleStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.complexStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexStatement([NotNull] SLangGrammarParser.ComplexStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.complexStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexStatement([NotNull] SLangGrammarParser.ComplexStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.let"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLet([NotNull] SLangGrammarParser.LetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.let"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLet([NotNull] SLangGrammarParser.LetContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput([NotNull] SLangGrammarParser.InputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput([NotNull] SLangGrammarParser.InputContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutput([NotNull] SLangGrammarParser.OutputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutput([NotNull] SLangGrammarParser.OutputContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.returnC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnC([NotNull] SLangGrammarParser.ReturnCContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.returnC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnC([NotNull] SLangGrammarParser.ReturnCContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] SLangGrammarParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] SLangGrammarParser.CallContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.ifC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfC([NotNull] SLangGrammarParser.IfCContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.ifC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfC([NotNull] SLangGrammarParser.IfCContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.whileC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileC([NotNull] SLangGrammarParser.WhileCContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.whileC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileC([NotNull] SLangGrammarParser.WhileCContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.repeatC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeatC([NotNull] SLangGrammarParser.RepeatCContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.repeatC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeatC([NotNull] SLangGrammarParser.RepeatCContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.exprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprList([NotNull] SLangGrammarParser.ExprListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.exprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprList([NotNull] SLangGrammarParser.ExprListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp([NotNull] SLangGrammarParser.ExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp([NotNull] SLangGrammarParser.ExpContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.simpleExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleExpr([NotNull] SLangGrammarParser.SimpleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.simpleExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleExpr([NotNull] SLangGrammarParser.SimpleExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] SLangGrammarParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] SLangGrammarParser.TermContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.signedFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSignedFactor([NotNull] SLangGrammarParser.SignedFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.signedFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSignedFactor([NotNull] SLangGrammarParser.SignedFactorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] SLangGrammarParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] SLangGrammarParser.FactorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.newC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewC([NotNull] SLangGrammarParser.NewCContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.newC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewC([NotNull] SLangGrammarParser.NewCContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.designator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDesignator([NotNull] SLangGrammarParser.DesignatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.designator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDesignator([NotNull] SLangGrammarParser.DesignatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.designatorStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDesignatorStatement([NotNull] SLangGrammarParser.DesignatorStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.designatorStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDesignatorStatement([NotNull] SLangGrammarParser.DesignatorStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.qualident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualident([NotNull] SLangGrammarParser.QualidentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.qualident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualident([NotNull] SLangGrammarParser.QualidentContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace SLangGrammar
