//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SLangGrammar.g4 by ANTLR 4.6.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SLangGrammar {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SLangGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5")]
[System.CLSCompliant(false)]
public interface ISLangGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeName([NotNull] SLangGrammarParser.TypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeName([NotNull] SLangGrammarParser.TypeNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.ptrType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPtrType([NotNull] SLangGrammarParser.PtrTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.ptrType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPtrType([NotNull] SLangGrammarParser.PtrTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.customType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomType([NotNull] SLangGrammarParser.CustomTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.customType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomType([NotNull] SLangGrammarParser.CustomTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScalarType([NotNull] SLangGrammarParser.ScalarTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScalarType([NotNull] SLangGrammarParser.ScalarTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.simpleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleType([NotNull] SLangGrammarParser.SimpleTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.simpleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleType([NotNull] SLangGrammarParser.SimpleTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayType([NotNull] SLangGrammarParser.ArrayTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayType([NotNull] SLangGrammarParser.ArrayTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.arrayDimention"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayDimention([NotNull] SLangGrammarParser.ArrayDimentionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.arrayDimention"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayDimention([NotNull] SLangGrammarParser.ArrayDimentionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] SLangGrammarParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] SLangGrammarParser.StartContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.moduleImport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleImport([NotNull] SLangGrammarParser.ModuleImportContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.moduleImport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleImport([NotNull] SLangGrammarParser.ModuleImportContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule([NotNull] SLangGrammarParser.ModuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule([NotNull] SLangGrammarParser.ModuleContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.moduleStatementsSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleStatementsSeq([NotNull] SLangGrammarParser.ModuleStatementsSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.moduleStatementsSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleStatementsSeq([NotNull] SLangGrammarParser.ModuleStatementsSeqContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.moduleDeclareSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleDeclareSeq([NotNull] SLangGrammarParser.ModuleDeclareSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.moduleDeclareSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleDeclareSeq([NotNull] SLangGrammarParser.ModuleDeclareSeqContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclare([NotNull] SLangGrammarParser.DeclareContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclare([NotNull] SLangGrammarParser.DeclareContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.variableDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDecl([NotNull] SLangGrammarParser.VariableDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.variableDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDecl([NotNull] SLangGrammarParser.VariableDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.simpleDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleDecl([NotNull] SLangGrammarParser.SimpleDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.simpleDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleDecl([NotNull] SLangGrammarParser.SimpleDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.arrayDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayDecl([NotNull] SLangGrammarParser.ArrayDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.arrayDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayDecl([NotNull] SLangGrammarParser.ArrayDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.ptrDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPtrDecl([NotNull] SLangGrammarParser.PtrDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.ptrDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPtrDecl([NotNull] SLangGrammarParser.PtrDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.constDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstDecl([NotNull] SLangGrammarParser.ConstDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.constDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstDecl([NotNull] SLangGrammarParser.ConstDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.moduleFieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleFieldDecl([NotNull] SLangGrammarParser.ModuleFieldDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.moduleFieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleFieldDecl([NotNull] SLangGrammarParser.ModuleFieldDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.typeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDecl([NotNull] SLangGrammarParser.TypeDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.typeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDecl([NotNull] SLangGrammarParser.TypeDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.typeInherit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeInherit([NotNull] SLangGrammarParser.TypeInheritContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.typeInherit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeInherit([NotNull] SLangGrammarParser.TypeInheritContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.typeFieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeFieldDecl([NotNull] SLangGrammarParser.TypeFieldDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.typeFieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeFieldDecl([NotNull] SLangGrammarParser.TypeFieldDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDecl([NotNull] SLangGrammarParser.FunctionDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDecl([NotNull] SLangGrammarParser.FunctionDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.thisHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThisHeader([NotNull] SLangGrammarParser.ThisHeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.thisHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThisHeader([NotNull] SLangGrammarParser.ThisHeaderContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.routineArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoutineArgList([NotNull] SLangGrammarParser.RoutineArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.routineArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoutineArgList([NotNull] SLangGrammarParser.RoutineArgListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.routineArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoutineArg([NotNull] SLangGrammarParser.RoutineArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.routineArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoutineArg([NotNull] SLangGrammarParser.RoutineArgContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.procedureDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureDecl([NotNull] SLangGrammarParser.ProcedureDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.procedureDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureDecl([NotNull] SLangGrammarParser.ProcedureDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.importHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportHead([NotNull] SLangGrammarParser.ImportHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.importHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportHead([NotNull] SLangGrammarParser.ImportHeadContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.statementSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementSeq([NotNull] SLangGrammarParser.StatementSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.statementSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementSeq([NotNull] SLangGrammarParser.StatementSeqContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] SLangGrammarParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] SLangGrammarParser.StatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.simpleStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleStatement([NotNull] SLangGrammarParser.SimpleStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.simpleStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleStatement([NotNull] SLangGrammarParser.SimpleStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.complexStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexStatement([NotNull] SLangGrammarParser.ComplexStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.complexStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexStatement([NotNull] SLangGrammarParser.ComplexStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.let"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLet([NotNull] SLangGrammarParser.LetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.let"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLet([NotNull] SLangGrammarParser.LetContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.ifC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfC([NotNull] SLangGrammarParser.IfCContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.ifC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfC([NotNull] SLangGrammarParser.IfCContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.whileC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileC([NotNull] SLangGrammarParser.WhileCContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.whileC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileC([NotNull] SLangGrammarParser.WhileCContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.repeatC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatC([NotNull] SLangGrammarParser.RepeatCContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.repeatC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatC([NotNull] SLangGrammarParser.RepeatCContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput([NotNull] SLangGrammarParser.InputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput([NotNull] SLangGrammarParser.InputContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutput([NotNull] SLangGrammarParser.OutputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutput([NotNull] SLangGrammarParser.OutputContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.returnC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnC([NotNull] SLangGrammarParser.ReturnCContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.returnC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnC([NotNull] SLangGrammarParser.ReturnCContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] SLangGrammarParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] SLangGrammarParser.CallContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprList([NotNull] SLangGrammarParser.ExprListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprList([NotNull] SLangGrammarParser.ExprListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] SLangGrammarParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] SLangGrammarParser.ExpContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.simpleExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleExpr([NotNull] SLangGrammarParser.SimpleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.simpleExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleExpr([NotNull] SLangGrammarParser.SimpleExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] SLangGrammarParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] SLangGrammarParser.TermContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] SLangGrammarParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] SLangGrammarParser.FactorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.newC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewC([NotNull] SLangGrammarParser.NewCContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.newC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewC([NotNull] SLangGrammarParser.NewCContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesignator([NotNull] SLangGrammarParser.DesignatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesignator([NotNull] SLangGrammarParser.DesignatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SLangGrammarParser.qualident"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualident([NotNull] SLangGrammarParser.QualidentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SLangGrammarParser.qualident"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualident([NotNull] SLangGrammarParser.QualidentContext context);
}
} // namespace SLangGrammar
